name = "circuitai-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "circuitai-api"

[env.staging]
name = "circuitai-api-staging"

[[env.production.kv_namespaces]]
binding = "CIRCUITS_KV"
id = "your-kv-namespace-id"

[[env.production.d1_databases]]
binding = "DB"
database_name = "circuitai-db"
database_id = "your-database-id"

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://your-app.pages.dev"
